### ISSUE TITLE
NOT an issue but THANK YOU

### ISSUE THREAD

**Issue by tswire** [cupshir/homebridge-aqua-connect-lite#1]
Great work and you have EXACT setup as me.  Got the lights working in Home app and would love if you get Aux 1 and Aux 2 working some day.  I have my slide and waterfall on those and would be awesome to use Home app to turn on and off.

**Comment by cupshir** [comment]
Nice! Glad to hear someone else is getting some use out of this. :-)  I will get Aux1 and Aux2 adde in the next week or so.

**Comment by tswire** [comment]
Awesome.  Look forward to it!  thanks again

**Comment by cupshir** [comment]
Sorry for the delay in this, I have made the changes in the code, but still need to test everything. Hoping to wrap it up this weekend.

**Comment by pateboyd** [comment]
I am looking for to testing it too. Any chance of getting the heater added?

**Comment by tswire** [comment]
I live in Canada so pool is closing soon but would love to test it out this weekend!!!  Thanks again

**Comment by tswire** [comment]
> Sorry for the delay in this, I have made the changes in the code, but still need to test everything. Hoping to wrap it up this weekend.

Any luck?  I would love to test before Nov 1st as my pool is closing then.  Appreciate all your work!

**Comment by cupshir** [comment]
Sorry for the delay. I got the update pushed out which will add Aux 1 and Aux 2. Let me know if you run into any issues with it.

**Comment by cupshir** [comment]
> I am looking for to testing it too. Any chance of getting the heater added?

Unfortunately, I do not have the heater, which makes developing and testing it difficult.  We are maybe going to get one and if I do then I will add that functionality for sure!

**Comment by tswire** [comment]
@cupshir Works like a charm!!!!  AWESOME work. Like others would love a better way to do the heater as it’s cumbersome to click through the app hit menu then over twice then up and down which is super delayed. If you can do that, this would be perfect.

**Comment by cupshir** [comment]
If someone wants to gift me a heater I will happily figure it out! lol. 

Thanks for the feedback and letting me know the updates worked! :-)

**Comment by tswire** [comment]
> If someone wants to gift me a heater I will happily figure it out! lol.
> 
> Thanks for the feedback and letting me know the updates worked! :-)

Hahahaha. Maybe I will donate something for next season!!

**Comment by ifeign** [comment]
If only I’d known about this after wrangling with this [Home Assistant version](https://github.com/amscanne/aqua-connect-local) . Thank you!!! I much prefer the simplicity of Homebridge
